# -*- coding: utf-8 -*-
from django.utils.translation import ugettext as _

DIAS_ANTI = (
    (5,5),
    (4,4),
    (3,3),
    (2,2),
    (1,1),
)

PORCENTAJE = (
    (0, 0),
    (10, 10),
    (20, 20),
    (30, 30),
    (40, 40),
    (50, 50),
    (60, 60),
    (70, 70),
    (80, 80),
    (90, 90),
    (100, 100),
)

SINO = (
    (True, _('Si')),
    (False, _('No'))
)

MSPN = (
    (1, _('Mucho')),
    (2, _('Suficiente')),
    (3, _('Poco')),
    (4, _('Nada')),
)

NACIONALIDAD = ((u'Afganist\xe1n', u'Afganist\xe1n'),
 ('Albania', 'Albania'),
 ('Alemania', 'Alemania'),
 ('Andorra', 'Andorra'),
 ('Angola', 'Angola'),
 ('Anguila', 'Anguila'),
 ('Antigua y Barbuda', 'Antigua y Barbuda'),
 ('Antillas Holandesas', 'Antillas Holandesas'),
 (u'Ant\xe1rtida', u'Ant\xe1rtida'),
 ('Arabia Saudita', 'Arabia Saudita'),
 ('Argelia', 'Argelia'),
 ('Argentina', 'Argentina'),
 ('Armenia', 'Armenia'),
 ('Aruba', 'Aruba'),
 ('Australia', 'Australia'),
 ('Austria', 'Austria'),
 (u'Azerbaiy\xe1n', u'Azerbaiy\xe1n'),
 ('Bahamas', 'Bahamas'),
 ('Bahrein', 'Bahrein'),
 ('Bangladesh', 'Bangladesh'),
 ('Barbados', 'Barbados'),
 ('Belarus', 'Belarus'),
 ('Belice', 'Belice'),
 ('Benin', 'Benin'),
 ('Bermudas', 'Bermudas'),
 ('Bhutan', 'Bhutan'),
 ('Bolivia', 'Bolivia'),
 ('Bosnia y Herzegovina', 'Bosnia y Herzegovina'),
 ('Botswana', 'Botswana'),
 ('Brasil', 'Brasil'),
 ('Brunei Darussalam', 'Brunei Darussalam'),
 ('Bulgaria', 'Bulgaria'),
 ('Burkina Faso', 'Burkina Faso'),
 ('Burundi', 'Burundi'),
 (u'B\xe9lgica', u'B\xe9lgica'),
 ('Cabo Verde', 'Cabo Verde'),
 (u'Camer\xfan', u'Camer\xfan'),
 (u'Canad\xe1', u'Canad\xe1'),
 ('Chad', 'Chad'),
 ('Chile', 'Chile'),
 ('Chipre', 'Chipre'),
 ('Colombia', 'Colombia'),
 ('Comoras', 'Comoras'),
 ('Congo', 'Congo'),
 ('Costa Rica', 'Costa Rica'),
 ('Costa de Marfil', 'Costa de Marfil'),
 ('Croacia', 'Croacia'),
 ('Cuba', 'Cuba'),
 ('Desconocido', 'Desconocido'),
 ('Dinamarca', 'Dinamarca'),
 ('Djibouti', 'Djibouti'),
 ('Dominica', 'Dominica'),
 ('Ecuador', 'Ecuador'),
 ('Egipto', 'Egipto'),
 ('El Salvador', 'El Salvador'),
 (u'Emiratos \xc1rabes Unidos', u'Emiratos \xc1rabes Unidos'),
 ('Eritrea', 'Eritrea'),
 ('Eslovaquia', 'Eslovaquia'),
 ('Eslovenia', 'Eslovenia'),
 (u'Espa\xf1a', u'Espa\xf1a'),
 ('Estados Federados de Micronesia', 'Estados Federados de Micronesia'),
 (u'Estados Unidos de Am\xe9rica', u'Estados Unidos de Am\xe9rica'),
 ('Estonia', 'Estonia'),
 (u'Etiop\xeda', u'Etiop\xeda'),
 (u'Ex Rep\xfablica yugoslava de Macedonia',
  u'Ex Rep\xfablica yugoslava de Macedonia'),
 ('Fiji', 'Fiji'),
 ('Filipinas', 'Filipinas'),
 ('Finlandia', 'Finlandia'),
 ('Francia', 'Francia'),
 ('Francia Metropolitana', 'Francia Metropolitana'),
 (u'Gab\xf3n', u'Gab\xf3n'),
 ('Gambia', 'Gambia'),
 ('Georgia', 'Georgia'),
 ('Ghana', 'Ghana'),
 ('Gibraltar', 'Gibraltar'),
 (u'Gran Breta\xf1a E Irlanda del Norte (Reino Unido)',
  u'Gran Breta\xf1a E Irlanda del Norte (Reino Unido)'),
 ('Granada', 'Granada'),
 ('Grecia', 'Grecia'),
 ('Groenlandia', 'Groenlandia'),
 ('Guadeloupe', 'Guadeloupe'),
 ('Guam', 'Guam'),
 ('Guatemala', 'Guatemala'),
 ('Guayana Francesa', 'Guayana Francesa'),
 ('Guinea', 'Guinea'),
 ('Guinea Ecuatorial', 'Guinea Ecuatorial'),
 ('Guinea-Bissau', 'Guinea-Bissau'),
 ('Guyana', 'Guyana'),
 (u'Hait\xed', u'Hait\xed'),
 ('Honduras', 'Honduras'),
 ('Hong Kong', 'Hong Kong'),
 (u'Hungr\xeda', u'Hungr\xeda'),
 ('India', 'India'),
 ('Indonesia', 'Indonesia'),
 ('Iraq', 'Iraq'),
 (u'Ir\xe1n', u'Ir\xe1n'),
 ('Isla Bouvet', 'Isla Bouvet'),
 ('Isla Christmas', 'Isla Christmas'),
 ('Isla Norfolk', 'Isla Norfolk'),
 ('Islandia', 'Islandia'),
 (u'Islas Caim\xe1n', u'Islas Caim\xe1n'),
 ('Islas Cocos (Keeling)', 'Islas Cocos (Keeling)'),
 ('Islas Cook', 'Islas Cook'),
 ('Islas Feroe', 'Islas Feroe'),
 ('Islas Georgias del Sur y Sandwich del Sur',
  'Islas Georgias del Sur y Sandwich del Sur'),
 ('Islas Heard y Mcdonald', 'Islas Heard y Mcdonald'),
 ('Islas Malvinas y dependencias', 'Islas Malvinas y dependencias'),
 ('Islas Marianas Septentrionales', 'Islas Marianas Septentrionales'),
 ('Islas Marshall', 'Islas Marshall'),
 ('Islas Remotas Menores de los Estados Unidos',
  'Islas Remotas Menores de los Estados Unidos'),
 (u'Islas Salom\xf3n', u'Islas Salom\xf3n'),
 ('Islas Svalbard y Jan Mayen', 'Islas Svalbard y Jan Mayen'),
 ('Islas Turcas y Caicos', 'Islas Turcas y Caicos'),
 (u'Islas V\xedrgenes (Estados Unidos)',
  u'Islas V\xedrgenes (Estados Unidos)'),
 (u'Islas V\xedrgenes Brit\xe1nicas', u'Islas V\xedrgenes Brit\xe1nicas'),
 ('Islas Wallis y Futuna', 'Islas Wallis y Futuna'),
 ('Israel', 'Israel'),
 ('Italia', 'Italia'),
 ('Jamaica', 'Jamaica'),
 (u'Jap\xf3n', u'Jap\xf3n'),
 ('Jordania', 'Jordania'),
 ('Kazajstan', 'Kazajstan'),
 ('Kenya', 'Kenya'),
 ('Kirguistan', 'Kirguistan'),
 ('Kiribati', 'Kiribati'),
 ('Kuwait', 'Kuwait'),
 ('Laos', 'Laos'),
 ('Lesotho', 'Lesotho'),
 ('Letonia', 'Letonia'),
 ('Liberia', 'Liberia'),
 ('Libia', 'Libia'),
 ('Liechtenstein', 'Liechtenstein'),
 ('Lituania', 'Lituania'),
 ('Luxemburgo', 'Luxemburgo'),
 (u'L\xedbano', u'L\xedbano'),
 ('Macao', 'Macao'),
 ('Madagascar', 'Madagascar'),
 ('Malasia', 'Malasia'),
 ('Malawi', 'Malawi'),
 ('Maldivas', 'Maldivas'),
 ('Mali', 'Mali'),
 ('Malta', 'Malta'),
 ('Marruecos', 'Marruecos'),
 ('Martinica', 'Martinica'),
 ('Mauricio', 'Mauricio'),
 ('Mauritania', 'Mauritania'),
 ('Mayotte', 'Mayotte'),
 ('Moldova', 'Moldova'),
 ('Mongolia', 'Mongolia'),
 ('Montserrat', 'Montserrat'),
 ('Mozambique', 'Mozambique'),
 ('Myanmar', 'Myanmar'),
 (u'M\xe9xico', u'M\xe9xico'),
 (u'M\xf3naco', u'M\xf3naco'),
 ('Namibia', 'Namibia'),
 ('Nauru', 'Nauru'),
 ('Nepal', 'Nepal'),
 ('Nicaragua', 'Nicaragua'),
 ('Nigeria', 'Nigeria'),
 ('Niue', 'Niue'),
 ('Noruega', 'Noruega'),
 ('Nueva Caledonia', 'Nueva Caledonia'),
 ('Nueva Zelanda', 'Nueva Zelanda'),
 (u'N\xedger', u'N\xedger'),
 (u'Om\xe1n', u'Om\xe1n'),
 (u'Pakist\xe1n', u'Pakist\xe1n'),
 ('Palau', 'Palau'),
 ('Palestina', 'Palestina'),
 (u'Panam\xe1', u'Panam\xe1'),
 (u'Pap\xfaa Nueva Guinea', u'Pap\xfaa Nueva Guinea'),
 ('Paraguay', 'Paraguay'),
 (u'Pa\xedses Bajos (Holanda)', u'Pa\xedses Bajos (Holanda)'),
 (u'Per\xfa', u'Per\xfa'),
 ('Pitcairn', 'Pitcairn'),
 ('Polinesia Francesa', 'Polinesia Francesa'),
 ('Polonia', 'Polonia'),
 ('Portugal', 'Portugal'),
 ('Puerto Rico', 'Puerto Rico'),
 ('Qatar', 'Qatar'),
 (u'Rep\xfablica Centroafricana', u'Rep\xfablica Centroafricana'),
 (u'Rep\xfablica Checa', u'Rep\xfablica Checa'),
 (u'Rep\xfablica Democr\xe1tica del Congo',
  u'Rep\xfablica Democr\xe1tica del Congo'),
 (u'Rep\xfablica Dominicana', u'Rep\xfablica Dominicana'),
 (u'Rep\xfablica Khmer Kampuchea', u'Rep\xfablica Khmer Kampuchea'),
 (u'Rep\xfablica Popular Democr\xe1tica de Corea (Corea del Norte)',
  u'Rep\xfablica Popular Democr\xe1tica de Corea (Corea del Norte)'),
 (u'Rep\xfablica Popular de China', u'Rep\xfablica Popular de China'),
 (u'Rep\xfablica de Corea (Corea del Sur)',
  u'Rep\xfablica de Corea (Corea del Sur)'),
 (u'Rep\xfablica de Irlanda', u'Rep\xfablica de Irlanda'),
 ('Reunion', 'Reunion'),
 ('Rumania', 'Rumania'),
 ('Rusia', 'Rusia'),
 ('Rwanda', 'Rwanda'),
 ('Sahara Occidental', 'Sahara Occidental'),
 ('Saint Kitts y Nevis', 'Saint Kitts y Nevis'),
 ('Samoa', 'Samoa'),
 ('Samoa Estadounidense', 'Samoa Estadounidense'),
 ('San Marino', 'San Marino'),
 ('San Pierre y Miquelon', 'San Pierre y Miquelon'),
 ('San Vicente y Las Granadinas', 'San Vicente y Las Granadinas'),
 ('Santa Elena y Dpendencias', 'Santa Elena y Dpendencias'),
 ('Santa Lucia', 'Santa Lucia'),
 ('Santo Tome y Principe', 'Santo Tome y Principe'),
 ('Senegal', 'Senegal'),
 ('Serbia y Montenegro', 'Serbia y Montenegro'),
 ('Seychelles', 'Seychelles'),
 ('Sierra Leona', 'Sierra Leona'),
 ('Singapur', 'Singapur'),
 ('Siria', 'Siria'),
 ('Somalia', 'Somalia'),
 ('Sri Lanka', 'Sri Lanka'),
 ('Sudan', 'Sudan'),
 (u'Sud\xe1frica', u'Sud\xe1frica'),
 ('Suecia', 'Suecia'),
 ('Suiza', 'Suiza'),
 ('Surinam', 'Surinam'),
 ('Swazilandia', 'Swazilandia'),
 ('Tailandia', 'Tailandia'),
 ('Taiwan', 'Taiwan'),
 ('Tanzania', 'Tanzania'),
 (u'Tayikist\xe1n', u'Tayikist\xe1n'),
 (u'Territorio Brit\xe1nico del Oc\xe9ano Indico',
  u'Territorio Brit\xe1nico del Oc\xe9ano Indico'),
 ('Territorios Franceses del Sur', 'Territorios Franceses del Sur'),
 ('Timor Oriental', 'Timor Oriental'),
 ('Togo', 'Togo'),
 ('Tokelau', 'Tokelau'),
 ('Tonga', 'Tonga'),
 ('Trinidad y Tobago', 'Trinidad y Tobago'),
 ('Tunez', 'Tunez'),
 (u'Turkmenist\xe1n', u'Turkmenist\xe1n'),
 (u'Turqu\xeda', u'Turqu\xeda'),
 ('Tuvalu', 'Tuvalu'),
 ('Ucrania', 'Ucrania'),
 ('Uganda', 'Uganda'),
 ('Urss', 'Urss'),
 ('Uruguay', 'Uruguay'),
 (u'Uzbekist\xe1n', u'Uzbekist\xe1n'),
 ('Vanuatu', 'Vanuatu'),
 ('Vaticano', 'Vaticano'),
 ('Venezuela', 'Venezuela'),
 ('Viet Nam', 'Viet Nam'),
 ('Yemen', 'Yemen'),
 ('Yugoslavia', 'Yugoslavia'),
 ('Zambia', 'Zambia'),
 ('Zimbabwe', 'Zimbabwe'),
 ('Zona Neutral', 'Zona Neutral'))
